/* eslint-disable */
/**
 * DO NOT EDIT — generated by `npm run gen:api` from
 * contracts/openapi/horizon-api.yaml (Horizon Public API v1.0.0).
 *
 * Regenerate after every contract change and commit the result.
 */

export interface paths {
    "/api/v1/admin/unrecognized-directions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Очередь пополнения перекрёстного словаря направлений
         * @description Формулировки, которых словарь направлений не знает, — сначала те, что спрашивают чаще.
         *
         *     Отвечает на вопрос, на который до появления журнала нельзя было ответить: чего словарю не
         *     хватает на самом деле. Догадка даёт словарь, покрывающий то, о чём подумал автор, и
         *     молчащий о том, что спрашивают аналитики.
         *
         *     Область — организация вызывающего, и берётся она из токена, а не из параметра: перечень
         *     направлений, которые исследует банк, — его исследовательская повестка.
         */
        get: operations["listUnrecognizedDirections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/directions/known": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Направления, которые система умеет соотнести с корпусом
         * @description Подсказка для пустого поля ввода. Система знает, какие формулировки распознаёт; аналитик,
         *     который этого не видит, гадает, а неудачная догадка стоит ему полного прогона анализа,
         *     заканчивающегося оговоркой «направление не распознано».
         *
         *     Список — подсказка, а не закрытый перечень: свободный ввод остаётся, потому что продукт
         *     обязан принимать направления, которых словарь ещё не знает. Именно для них заведена очередь
         *     пополнения.
         *
         *     Пустой список — допустимый ответ: подсказка помогает, но не является условием работы экрана.
         */
        get: operations["listKnownDirections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/directions/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Понимает ли система эту формулировку — до запуска анализа
         * @description Тот же вердикт, что стоит в готовом отчёте оговоркой «направление не распознано», но
         *     выданный вовремя. Прежде аналитик узнавал его после полутора минут ожидания и списанного
         *     слота квоты — и, узнав, оставался с тем же вопросом, что и до запуска: как тогда написать.
         *
         *     Запрет на запуск отсюда не следует. Список направлений — подсказка, а не закрытый перечень:
         *     продукт обязан принимать формулировки, которых словарь ещё не знает, иначе пополнять его
         *     будет неоткуда.
         *
         *     Недоступность движка отвечает `recognized: true` намеренно: вердикта в этом случае нет, а
         *     показать «не распознано» значило бы соврать. Сомнение трактуется в пользу аналитика.
         */
        get: operations["resolveDirection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Какие функции включены в этой сборке
         * @description Клиент читает это один раз и скрывает выключенные функции, чтобы выключенная функция не показывала элемент управления, отвечающий 404.
         */
        get: operations["listFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ingestion-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** История прогонов сбора */
        get: operations["listIngestionRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Полный отчёт по трендам */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{reportId}/delta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Что изменилось с предыдущей версии отчёта
         * @description Состав ТОП, размеченный на появившиеся, выбывшие и оставшиеся темы, с изменением ранга и балла у оставшихся. Отдельный ресурс, а не поле отчёта: дельта нужна при повторном чтении, и вкладывать её значило бы поднимать вторую версию из хранилища на каждый запрос отчёта.
         *
         *     Темы сопоставляются по `trendKey`, а не по заголовку: заголовок — это подпись кластера, и она законно меняется при том же предмете, поэтому сравнение по нему выдало бы улучшение названия за событие в реальности.
         */
        get: operations["getReportDelta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{reportId}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Почему темы нет в отчёте
         * @description Прослеживает указанные термины через конвейер анализа и сообщает, на какой стадии каждый из них был отброшен и по какой причине. Отвечает на вопрос «я знаю, что эта технология существует, — почему её нет в отчёте?», который иначе остаётся без ответа и разрушает доверие к ранжированию.
         *
         *     Ответ строится повторным прогоном анализа на том же срезе корпуса — это минуты, поэтому запрос не ждёт движка: пока прогон идёт, ответ — 202 с `Retry-After`, и клиент повторяет тот же запрос, пока не получит 200. Одинаковые вопросы сводятся к одному прогону. Число терминов ограничено пятью.
         */
        get: operations["explainReportTerms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{reportId}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Экспорт отчёта
         * @description Три формата под три разных читателя: JSON для скрипта, CSV для Excel, Markdown для человека, который переносит отчёт в записку комитету. Последний нужен потому, что именно на этом переносе оговорки терялись: вручную переносят выводы, а не сноски.
         *
         *     Во всех форматах отсутствуют личные пометки аналитика: файл передают дальше, а дословный комментарий, написанный для себя, в чужих руках — это не то, что человек соглашался опубликовать. Документ датируется анализом, а не моментом выгрузки, поэтому две выгрузки одного отчёта дают одинаковые байты.
         */
        get: operations["exportReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{reportId}/trends/{trendKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Один тренд с полной детализацией */
        get: operations["getReportTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/{reportId}/trends/{trendKey}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Оценить тренд */
        put: operations["submitTrendFeedback"];
        post?: never;
        /**
         * Снять свою пометку с темы
         * @description Отдельная операция, а не вердикт «полезно». Пометка «не технология» стала действием с последствиями: движок убирает такую тему до отбора в ТОП-N, и в отчёте её больше нет. Отменить это, объявив тему полезной, значит сделать утверждение, которого аналитик не делал, — а его унаследует следующий отчёт. Снимается только собственная пометка: ключи, которых аналитик не помечал, отвергаются, иначе появился бы способ писать в разметку произвольные строки.
         */
        delete: operations["withdrawTrendFeedback"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * История запросов организации
         * @description Запросы всей организации, а не только собственные. Отчёты, переиспользование готового и идущий анализ уже общие — история была последним местом, где работа притворялась личной, и тем местом, где расчёт, к которому присоединился коллега, исчезал вместе с закрытой вкладкой.
         *
         *     У каждой строки есть `mine`: экран сменил смысл, и молчание об этом было бы худшей подачей — аналитик, увидевший у себя то, чего не запускал, решит, что под его учётной записью работают.
         */
        get: operations["listResearchRequests"];
        put?: never;
        /** Запустить анализ технологического направления */
        post: operations["submitResearchRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research-requests/{requestId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Статус запроса */
        get: operations["getResearchRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research-requests/{requestId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Отменить выполняющийся запрос */
        post: operations["cancelResearchRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research-requests/{requestId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Поток прогресса (Server-Sent Events)
         * @description `text/event-stream`. Типы событий: `progress`, `completed`, `failed`, `heartbeat`.
         *     Данные каждого события — JSON объекта `ResearchRequestView`.
         *     При невозможности установить поток клиент обязан деградировать до опроса `GET /research-requests/{id}`.
         */
        get: operations["streamResearchRequestEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research-requests/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Остаток часового бюджета
         * @description Сколько запросов ещё можно сделать. Оценка, а не обязательство: окно скользящее, а организационная половина общая — коллега может потратить слот между ответом и нажатием.
         *
         *     `known: false` вместо нулей, когда счётчик недоступен. Квота fail-open: запросы всё равно проходят, и сказать «бюджета нет» значило бы заставить интерфейс утверждать обратное тому, что делает система.
         */
        get: operations["getQuota"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сохранённые направления */
        get: operations["listSavedDomains"];
        put?: never;
        /** Сохранить направление */
        post: operations["saveDomain"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-domains/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Удалить сохранённое направление */
        delete: operations["deleteSavedDomain"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-domains/{id}/seen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Отметить направление просмотренным
         * @description Отдельное действие, а не побочный эффект загрузки радара: радар открывают, чтобы решить, куда смотреть, и пометить в этот момент всё просмотренным значило бы стереть ответ на вопрос, ради которого пришли.
         *
         *     Отметка личная: визит коллеги не гасит чужую новизну.
         */
        post: operations["markDirectionSeen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-domains/digest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Состояние всех отслеживаемых направлений
         * @description Одна строка на отслеживаемое направление: сводка, сколько тем вошло и выбыло с прошлой версии, и первые темы для узнавания. Экран, который аналитик открывает утром, чтобы понять, куда потратить день.
         *
         *     Собирается на сервере, потому что клиентская альтернатива — два запроса на направление: пятьдесят сохранённых превратились бы в сотню обращений и экран, заполняющийся секундами.
         *
         *     Направление, по которому анализ ещё не запускался, сохраняет свою строку без сводки: «здесь ещё ничего не считалось» — это и есть ответ, за которым пришли.
         */
        get: operations["getRadarDigest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-domains/overlap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Темы, встречающиеся сразу в нескольких направлениях
         * @description Тема, найденная в одном направлении, — наблюдение. Та же тема, независимо всплывшая в двух несмежных направлениях, — конвергенция: признак, что технология выходит за пределы своей ниши. Методология этого не видит по построению: индикаторы считаются внутри корпуса одного запроса.
         *
         *     Баллов здесь нет намеренно. Балл нормирован внутри своего корпуса (§12 методологии), у баллов разных направлений нет общей шкалы, и число, показанное рядом с другим, будет сравнено читателем независимо от подписи. Сопоставляется состав и позиция.
         *
         *     Пустой список при `directionsCompared` меньше двух означает «сравнивать пока не с чем», а не «пересечений нет»; это разные ответы, и клиент обязан их различать.
         */
        get: operations["getDirectionOverlap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/saved-domains/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Поставить на пересчёт все отслеживаемые направления
         * @description Радар полезен ровно настолько, насколько свеж. Обновлять двадцать направлений по одному — работа, которую никто не делает, и экран начинает показывать позапрошлый квартал с уверенным видом.
         *
         *     Отвечает 200 со строкой на каждое направление даже если не поставлено ни одно: три исхода из четырёх не являются отказом, а HTTP-ошибка заставила бы клиента гадать, что произошло с каждым направлением. Пакет подчиняется той же квоте и тому же переиспользованию свежего результата, что и одиночный запуск, — иначе кнопка стала бы способом обойти лимит.
         */
        post: operations["refreshRadar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Источники данных и их состояние */
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/{sourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить настройки источника
         * @description Требуется роль `RESEARCHER` или `ADMIN`.
         */
        patch: operations["updateSource"];
        trace?: never;
    };
    "/api/v1/sources/{sourceId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Запустить прогон сбора вручную */
        post: operations["triggerIngestionRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sources/openalex/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Суммарный остаток дневной квоты OpenAlex по настроенным ключам */
        get: operations["getOpenAlexQuota"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/topics/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Писали ли мы про эту тему раньше
         * @description Корпус отчётов организации — самое дорогое, что производит продукт, и до сих пор он был доступен только на запись. Повторное использование свежего отчёта отвечает на вопрос «это же самое направление», пересечение направлений смотрит лишь портфель одного аналитика и лишь последние версии, история ищет по формулировкам запросов. Тема, найденная полгода назад коллегой в другом направлении, не находилась ничем.
         *
         *     Совпадение — подстрока названия темы без учёта регистра. Морфология и веса требуют настройки, подтвердить которую нечем, а ненастроенная выдача отвечает уверенно и неверно.
         *
         *     Границей выступает организация. Порядок детерминирован: сначала темы, всплывшие в большем числе направлений, затем по лучшему месту в рейтинге, затем по ключу темы. Баллов нет нигде — балл нормирован внутри своего корпуса, и рядом с другим он был бы сравнён читателем независимо от подписи.
         */
        get: operations["searchTopics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalysisParameters: {
            /** @default false */
            includeMature?: boolean;
            /** @default 0 */
            minConfidence?: number;
            /**
             * @description Режим анализа. `fast` — ответ за 20 минут (SLA ТЗ): глубокое исследование получает 5,5 минуты. `quality` — до 30–40 минут: глубокое исследование читает втрое больше страниц за 20 минут, дедлайн запроса — 40 минут.
             *
             *     Часть идентичности вопроса: быстрый и качественный ответы на одно направление — два разных ответа, и готовый отчёт одного режима не переиспользуется как ответ другого. Незнакомое имя — 400 с перечнем известных.
             * @default fast
             * @enum {string}
             */
            mode?: "fast" | "quality";
            /** @description Пустой список — все доступные классы */
            sourceClasses?: components["schemas"]["SourceClass"][];
            /** @default 15 */
            topN?: number;
            /** @default 7 */
            yearsWindow?: number;
        };
        AnalysisProgress: {
            message?: string;
            percent: number;
            /** @enum {string} */
            stage: "QUEUED" | "COLLECTING" | "ANALYZING" | "ASSEMBLING" | "DONE";
            /** Format: date-time */
            updatedAt?: string;
        };
        CaseExample: {
            /**
             * @description Какое из трёх правил методологии §8 подобрало пример. Патент означает, что организация закрепила право на применение; публикация — что она над темой работает, и внедрение из этого не следует. Отсутствует у отчётов, выпущенных до появления поля.
             * @enum {string}
             */
            basis?: "PATENT" | "CORPORATE_PUBLICATION" | "ACADEMIC_GROUP";
            country?: string;
            evidenceIndex: number;
            organization: string;
            /** @enum {string} */
            organizationType?: "COMPANY" | "UNIVERSITY" | "RESEARCH_INSTITUTE" | "GOVERNMENT" | "NONPROFIT";
            summary?: string;
        };
        Coverage: {
            candidatesEvaluated?: number;
            /** @default false */
            corpusTruncated?: boolean;
            /** @default true */
            directionRecognized?: boolean;
            directionSuggestions?: string[];
            documentsAnalyzed: number;
            exclusions?: {
                /** @description Стадия конвейера, она же код причины */
                code: string;
                count: number;
                examples?: string[];
                /** @description Формулировка для читателя, по-русски */
                reason: string;
            }[];
            partial: boolean;
            sourcesUsed: string[];
            /** @default 0 */
            suppressedByAnalyst?: number;
            unavailableSources?: string[];
            /** Format: date */
            windowFrom?: string;
            /** Format: date */
            windowTo?: string;
        };
        DirectionOverlap: {
            /** @description Сколько направлений участвовало — то есть имеет отчёт. */
            directionsCompared: number;
            /** @description Сколько отслеживаемых направлений не участвовало, потому что анализ по ним не запускался. Названо числом, а не молчанием: иначе «пересечений нет» читалось бы как утверждение о предметной области. */
            directionsSkipped: number;
            topics: components["schemas"]["SharedTopic"][];
        };
        /**
         * @description Направление в тех немногих величинах, за которые аналитику отвечать вслух. Всё выведено из самого отчёта; сгенерированных утверждений здесь нет намеренно — фразу «поле бурно растёт» нельзя проверить, а сводка существует для того, чтобы её повторил тот, с кого спросят.
         *
         *     Оговорки (`lowEvidenceCount`, `unavailableSources`) — обязательные поля, а не приложение: оговорка, которую можно не прислать, не будет прислана ровно тогда, когда она важна.
         */
        DirectionPortrait: {
            /** @description Все стадии методологии в её собственном порядке, включая нулевые: отсутствие строки «зрелые: 0» читается как «не считали», а порядок по величине менялся бы между отчётами. */
            byLifecycleStage: {
                count: number;
                stage: string;
            }[];
            /** @description Сколько кандидатов дошло до оценки. «15 из 4000» и «15 из 18» — разные утверждения. */
            candidatesEvaluated: number;
            /** @default true */
            directionRecognized?: boolean;
            /** @description Сколько тем в ТОП держится на тонкой доказательной базе. */
            lowEvidenceCount: number;
            /** @description Медиана, а не среднее: одна тема 1998 года сдвинула бы среднее на годы и не описала бы ни одной реальной темы. null для пустого отчёта. */
            medianFirstMentionYear?: number | null;
            partial: boolean;
            sourcesUsed: string[];
            trendsInReport: number;
            /** @description Чего в выводе заведомо нет. */
            unavailableSources: string[];
            /** Format: date */
            windowFrom: string;
            /** Format: date */
            windowTo: string;
        };
        /**
         * @description Вердикт по формулировке направления, выданный до запуска анализа.
         * @example {
         *       "recognized": false,
         *       "suggestions": [
         *         "квантовые вычисления",
         *         "квантовая криптография"
         *       ]
         *     }
         */
        DirectionResolution: {
            /**
             * @description Движок соотнёс формулировку со словарём предметных кодов корпуса. `true` при
             *     недоступном движке — вердикта нет, и выдумывать его нельзя.
             */
            recognized: boolean;
            /**
             * @description Ближайшие известные формулировки. Пусто, когда ничего похожего нет: подсказка наугад
             *     хуже её отсутствия, потому что выглядит как знание.
             */
            suggestions: string[];
        };
        EmergenceAssessment: {
            confidence: number;
            indicators: components["schemas"]["IndicatorScore"][];
            lowEvidence: boolean;
            rankStability?: components["schemas"]["RankStability"];
            score: number;
        };
        Evidence: {
            authors?: string;
            citationCount?: number | null;
            /**
             * @description Уровень доверенности источника — требование ТЗ к отображению каждого источника. Выводится движком от класса источника и хоста ссылки: официальный домен ведомства или университета сильнее класса в обе стороны, служба распространения пресс-релизов — слабее. `MEDIUM` у отчётов, выпущенных до появления поля.
             * @default MEDIUM
             * @enum {string}
             */
            credibility?: "HIGH" | "MEDIUM" | "LOW";
            /** @description Правило, присвоившее уровень, словами. ТЗ допускает показывать «уровень доверенности либо критерии его определения» — показываются оба: ярлык без основания читатель проверить не может, а проверяемость утверждений и есть то, чем продукт отличается от списка слов. */
            credibilityBasis?: string;
            doi?: string;
            externalId?: string;
            /**
             * @description Самостоятельное ли это свидетельство. `false` у перепечаток пресс-релизов, соцсетей и личных площадок: десять сайтов, перепечатавших один релиз, — один источник, а не десять.
             * @default true
             */
            independent?: boolean;
            /** @description Язык оригинала, ISO 639-1. ТЗ требует показывать его у каждого источника, и требование содержательное: русскоязычное резюме зарубежного материала имеет смысл только вместе с указанием, с какого языка оно сделано. Отсутствует, когда источник языка не сообщил. */
            language?: string;
            organization?: string;
            organizationCountry?: string;
            /** Format: date */
            publishedOn: string;
            relevance?: number;
            snippet?: string;
            sourceClass: components["schemas"]["SourceClass"];
            sourceId: string;
            title: string;
            /** Format: uri */
            url: string;
        };
        ExplanationItem: {
            text: string;
            title: string;
        };
        FailureInfo: {
            /**
             * @example SAGA_TIMEOUT
             * @example NO_DOCUMENTS_FOUND
             * @example ANALYSIS_FAILED
             */
            code: string;
            message: string;
            retryable: boolean;
        };
        FeatureFlag: {
            /** @description Что именно исчезнет — решение принимают по эффекту, а не по имени. */
            description?: string;
            enabled: boolean;
            /** @description Стабильный идентификатор — он же ключ конфигурации и в интерфейсе. */
            key: string;
            /** @description `default` — применено объявленное умолчание, `override` — значение задано конфигурацией. При разборе инцидента это разница между «кто-то выключил» и «никогда не включалось». */
            source?: string;
            title: string;
        };
        FoundTopic: {
            /** @description Лучшее (наименьшее) место темы среди её вхождений */
            bestRank: number;
            /** @description В скольких разных направлениях тема встретилась. Главный признак силы: в одном —  наблюдение, в двух несмежных — конвергенция. */
            directions: number;
            /** @description Сколько вхождений не показано; ноль, если показаны все */
            hiddenOccurrences: number;
            occurrences: components["schemas"]["TopicOccurrence"][];
            /** @description Название из самого свежего вхождения: тема могла быть переименована между версиями, и старое имя было бы ответом про прошлое. */
            title: string;
            trendKey: string;
        };
        /**
         * @description Вклад одного индикатора. `multiplier = value^weight`; итоговый балл = 100 × произведение множителей.
         *     `shortfallShare` — нормированная доля «недобора» (что сильнее всего ограничивает балл).
         */
        IndicatorScore: {
            /** @description Сырые величины: наклон регрессии, число организаций, энтропия и т. п. */
            diagnostics?: {
                [key: string]: unknown;
            };
            /** @description Человекочитаемое пояснение с фактическими числами */
            explanation?: string;
            multiplier: number;
            /** @enum {string} */
            name: "novelty" | "growth" | "diffusion" | "weakness" | "coherence" | "impact";
            shortfallShare: number;
            value: number;
            weight: number;
        };
        IngestionRunPage: components["schemas"]["PageMeta"] & {
            content: components["schemas"]["IngestionRunView"][];
        };
        IngestionRunView: {
            documentsCreated?: number;
            documentsDuplicate?: number;
            documentsFetched?: number;
            documentsRejected?: number;
            errorCode?: string | null;
            errorMessage?: string | null;
            /** Format: date-time */
            finishedAt?: string | null;
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            mode?: "INCREMENTAL" | "BACKFILL" | "ON_DEMAND";
            sourceId: string;
            /** Format: date-time */
            startedAt: string;
            /** @enum {string} */
            status: "RUNNING" | "COMPLETED" | "PARTIAL" | "FAILED";
        };
        /** @enum {string} */
        LifecycleStage: "EMBRYONIC" | "EMERGING" | "ACCELERATING" | "MATURING";
        /**
         * @description Русский слой карточки: перевод **рядом** с оригиналом, а не вместо него.
         *
         *     ТЗ требует двух вещей одновременно: «вся аналитическая выдача должна быть представлена на
         *     русском языке» и «для зарубежного материала … сохранив оригинальное название, ссылку, дату
         *     публикации и язык источника». Поэтому русская строка дополняет, а не заменяет: аналитик,
         *     который пойдёт проверять источник, обязан искать в нём то слово, которое там написано.
         *
         *     Модель называется и вид обработки различается — тоже по ТЗ: «при использовании
         *     автоматического перевода или генеративного резюме это должно быть отмечено возле
         *     источника». Перевод названия и пересказ абстракта имеют разную надёжность.
         *
         *     Отсутствует, когда сервис моделей был выключен или недоступен: отчёт при этом полон и
         *     верен — он просто по-английски.
         */
        Localization: {
            benefit?: string;
            definition?: string;
            /** @description Русские названия источников по порядку элементов evidence */
            evidenceTitles?: string[];
            problem?: string;
            /** @description Тема, сформулированная как тренд: одно русское предложение о том, что меняется и в какую сторону. Термин из двух-четырёх слов отвечает на вопрос «о чём», предложение — «что происходит». Всегда генеративный пересказ фрагментов источников темы и её ряда по годам; предложение с числом, которого нет во входе, отбрасывается. Отсутствует, когда модель не ответила или ответ не прошёл проверку. */
            statement?: string;
            /** @description Модель, сформулировавшая тренд (раскрытие по ТЗ §3.1) */
            statementModel?: string;
            /** @enum {string} */
            textMode?: "MACHINE" | "GENERATIVE";
            textModel?: string;
            title?: string;
            /**
             * @description Вид обработки: автоматический перевод или генеративный пересказ
             * @enum {string}
             */
            titleMode?: "MACHINE" | "GENERATIVE";
            /** @description Модель, переведшая название (раскрытие по ТЗ §3.1) */
            titleModel?: string;
        };
        /** @description Мотивация тренда: какую проблему решает и какое преимущество даёт */
        Motivation: {
            /** @description Индексы элементов evidence, из которых извлечены формулировки */
            attributions?: {
                evidenceIndex: number;
                /** @description Предложение, взятое именно из этого документа. Формулировка склеивается из предложений разных статей, и без привязки к предложению ссылка указывает на абзац целиком. Отсутствует у отчётов, выпущенных до появления поля. */
                sentence?: string;
                /** @enum {string} */
                statement: "problem" | "benefit";
            }[];
            benefit: string;
            problem: string;
        };
        OpenAlexQuota: {
            /** Format: date-time */
            checkedAt: string;
            keysChecked: number;
            keysConfigured: number;
            /** Format: int64 */
            limitCredits: number;
            /** Format: int64 */
            remainingCredits: number;
            /** Format: date-time */
            resetsAt?: string | null;
        };
        PageMeta: {
            page: number;
            size: number;
            /** Format: int64 */
            totalElements: number;
            totalPages: number;
        };
        /** @description RFC 9457 Problem Details */
        Problem: {
            detail?: string;
            errors?: {
                field: string;
                message: string;
                rejectedValue?: unknown;
            }[];
            instance?: string;
            retryable?: boolean;
            status: number;
            /** Format: date-time */
            timestamp?: string;
            title: string;
            traceId?: string;
            /**
             * Format: uri
             * @example https://horizon.dev/problems/validation-error
             */
            type: string;
        };
        Quota: {
            /** @description Удалось ли прочитать счётчик. При `false` остальные поля отсутствуют. */
            known: boolean;
            organizationLimit?: number;
            /** @description Общий с коллегами. */
            organizationRemaining?: number;
            /** @description Меньший из двух остатков — тот, что кончится раньше, и есть тот, что остановит аналитика. */
            remaining?: number;
            userLimit?: number;
            userRemaining?: number;
        };
        RadarDigest: {
            /** Format: date-time */
            analysedAt?: string;
            /** @description Сколько тем не было в предыдущей версии отчёта. */
            entered: number;
            /** @description Первые темы отчёта — чтобы узнать направление, не открывая его. */
            headline: string[];
            /** @description Сколько тем выбыло из ТОП. */
            left: number;
            portrait?: components["schemas"]["DirectionPortrait"];
            query: string;
            /**
             * Format: uuid
             * @description Отсутствует, если по направлению ещё не было анализа.
             */
            reportId?: string;
            /**
             * @description Отчёт этого направления недоступен смотрящему — например, его запускал коллега, а аналитик вышел из организации. Отличается от «ни разу не анализировали», где отсутствует reportId: там анализа не было, здесь он был, а прав на чтение больше нет. Строка при этом остаётся: исчезнув, она оставила бы аналитика гадать, сохранял ли он направление вообще.
             * @default false
             */
            reportUnavailable?: boolean;
            /** Format: uuid */
            savedDomainId: string;
            /**
             * Format: date-time
             * @description Когда вы в последний раз открывали это направление. Отсутствует, если ни разу — и тогда направление **не** считается непросмотренным: иначе новичок открыл бы радар и увидел двадцать «новых» строк, среди которых нет ни одной новости.
             *
             *     Отдаётся момент, а не готовый флаг: сравнение с `analysedAt` — одна операция, а флаг сервер не смог бы посчитать, не спросив о текущем времени.
             */
            seenAt?: string;
        };
        RadarRefresh: {
            /**
             * @description `accepted` — поставлено в очередь. `already-running` — анализ по этому направлению уже идёт, второй не запущен и квота не списана. `quota-exceeded` — часовой лимит исчерпан. `failed` — отказ по собственной причине направления.
             *
             *     Исхода «переиспользован готовый результат» здесь нет: пакетный пересчёт принудителен — кнопка заводилась ради обновления, и отвечать «уже свежее» на все направления сразу значит не делать ничего. Каждое направление расходует слот квоты.
             *
             *     Строка, а не закрытый enum: исход показывается пользователю, и появление нового не должно ломать уже собранных клиентов.
             */
            outcome: string;
            query: string;
            /** @description Заполнено для `quota-exceeded` и `failed`. */
            reason?: string;
            /**
             * Format: uuid
             * @description Есть для `accepted` и `already-running` — по нему клиент следит за анализом.
             */
            requestId?: string;
            /** Format: uuid */
            savedDomainId: string;
        };
        RankedTrend: {
            assessment: components["schemas"]["EmergenceAssessment"];
            burst?: {
                startPeriod?: string | null;
                weight?: number | null;
            };
            caseExample?: components["schemas"]["CaseExample"];
            definition: string;
            /**
             * @description Доля документов темы, отнесённых источниками к направлению отчёта.
             *
             *     Величина, на которой держится отбор темы в отчёт. У настоящих тем направления она около
             *     двух третей; тема с седьмой частью попадает в отчёт потому, что для узкого направления
             *     планка опускается почти до нуля. Статистика их не разделяет — человек разделяет сразу,
             *     если величину показать. Отсутствует, когда отбор шёл не по предметным кодам.
             */
            directionShare?: number;
            evidence: components["schemas"]["Evidence"][];
            /** @description Почему тема — слабый сигнал и почему у неё такая уверенность: строки «заголовок — пояснение», собранные движком из голосов экспертной стадии, вкладов в балл, расчёта уверенности и источников карточки. Пусто у отчётов, выпущенных до появления объяснения. */
            explanation?: components["schemas"]["ExplanationItem"][];
            feedback?: components["schemas"]["TrendFeedbackView"];
            /** @description Первый достоверный год темы по BRULE-2: не меньше двух документов из не меньше чем двух организаций. Это не год первого упоминания вообще — одиночные упоминания бывают раньше: по эталонному корпусу у 71 темы из 90, у 21 на два года и больше. Имя поля оставлено прежним намеренно: переименование сломало бы потребителей ради названия, а различие несут это описание и все подписи в интерфейсе. */
            firstMentionYear: number;
            lifecycleStage: components["schemas"]["LifecycleStage"];
            localization?: components["schemas"]["Localization"];
            /**
             * @description Все источники темы низкой доверенности. ТЗ: такие сведения «не должны быть единственным основанием для включения технологии в итоговую выдачу… либо сопровождаться отметкой о пониженной доверенности». Первую половину закрывает правило движка, отсекающее тему без научно-технической основы вовсе; вторую — эта отметка.
             * @default false
             */
            lowCredibilityOnly?: boolean;
            motivation: components["schemas"]["Motivation"];
            rank: number;
            timeline: components["schemas"]["TimelinePoint"][];
            title: string;
            totalDocuments: number;
            trendKey: string;
        };
        /**
         * @description Лучшее и худшее место темы при разумных изменениях весов индикаторов (методология §16).
         *
         *     Веса шести индикаторов выбраны экспертно, и без этого диапазона утверждение «тема третья»
         *     неотличимо от следствия того, как взвесили. Отсутствие поля означает «устойчивость не
         *     измерялась» — так приходят отчёты, выпущенные до появления проверки, — а не «неустойчиво».
         */
        RankStability: {
            best: number;
            worst: number;
        };
        ReportDelta: {
            /** @description Темы, которых не было в предыдущей версии. Порядок — по рангу в текущей. */
            entered: components["schemas"]["ReportDeltaEntry"][];
            /** @description Темы, выбывшие из ТОП. Порядок — по рангу в предыдущей версии. */
            left: components["schemas"]["ReportDeltaEntry"][];
            /**
             * Format: uuid
             * @description Отчёт, с которым сравнивали. Отсутствует, если сравнение не выполнялось.
             */
            previousReportId?: string;
            previousVersion?: number;
            /** @description Темы, присутствующие в обеих версиях. Порядок — по росту в ранге, то есть ускорившиеся первыми. */
            stayed: components["schemas"]["ReportDeltaEntry"][];
            /**
             * @description Заполнено ровно тогда, когда сравнение не выполнялось, и является частью контракта, а не пустым ответом: пустые группы читаются как «ничего не изменилось» — содержательное утверждение, противоположное «сравнить не с чем» и «сравнивать нельзя».
             *
             *     `no-previous-version` — это первая версия отчёта. `methodology-changed` — версия методологии изменилась между запусками, и разность баллов была бы изменением линейки, а не мира.
             *
             *     Тип — строка, а не закрытый enum, намеренно: причина показывается пользователю, и появление новой не должно ломать уже собранных клиентов. Так же сделаны `stage` и `outcome` в `TermExplanation`.
             */
            unavailableReason?: string;
        };
        ReportDeltaEntry: {
            /** @description Позиция в той версии, где тема присутствует. */
            rank: number;
            /** @description На сколько позиций тема поднялась (`ранг_прежний − ранг_текущий`), поэтому положительное значение читается как «выросла», хотя ранг считается вниз. Отсутствует для тем, представленных лишь в одной версии: прежнего ранга нет, а ноль читался бы как «удержала позицию». */
            rankChange?: number | null;
            score: number;
            /** @description Изменение балла со знаком; отсутствует при том же условии. */
            scoreChange?: number | null;
            title: string;
            trendKey: string;
        };
        ResearchRequestPage: components["schemas"]["PageMeta"] & {
            content: components["schemas"]["ResearchRequestView"][];
        };
        ResearchRequestView: {
            etaSeconds?: number | null;
            failure?: components["schemas"]["FailureInfo"];
            /** Format: date-time */
            finishedAt?: string | null;
            /**
             * @description Новой работы не начато. Один бит на три разных случая, поэтому рядом едет `outcome`.
             * @default false
             */
            fromCache?: boolean;
            /** Format: uuid */
            id: string;
            /**
             * @description Запустил ли этот запрос тот, кто смотрит. Приходит только в списке: у одного запроса вопрос «чей он» не стоит — туда приходят по ссылке на конкретный расчёт.
             *
             *     Имени автора здесь нет намеренно: оно живёт в контексте учётных записей, и копия здесь устарела бы при первом же переименовании. Система утверждает ровно то, что знает сама.
             */
            mine?: boolean;
            normalizedQuery?: string;
            /**
             * @description Чем закончилась отправка. `accepted` — запущен новый анализ (ответ 202). `already-running` — по этому направлению у вас уже шёл расчёт, он и возвращён; второй не запущен и квота не списана. `reused` — переиспользован готовый отчёт. `idempotent-replay` — сработал `Idempotency-Key`.
             *
             *     Есть только в ответе на отправку: при чтении запроса отправки не было, и поле опущено. Строка, а не закрытый enum, по той же причине, что и у исхода пересчёта.
             */
            outcome?: string;
            parameters: components["schemas"]["AnalysisParameters"];
            /** @default false */
            partial?: boolean;
            progress: components["schemas"]["AnalysisProgress"];
            query: string;
            /** Format: uuid */
            reportId?: string | null;
            /**
             * Format: uuid
             * @description Кто запустил запрос. Идентификатор, а не имя: имя принадлежит контексту учётных записей, и копия здесь устарела бы при первом переименовании — клиент разрешает его по справочнику организации.
             *
             *     Приходит только в списке, как и `mine`. Если справочник недоступен, остаётся `mine`, которого достаточно, чтобы список работал.
             */
            requestedBy?: string;
            status: components["schemas"]["ResearchStatus"];
            /** Format: date-time */
            submittedAt: string;
        };
        /** @enum {string} */
        ResearchStatus: "PENDING" | "COLLECTING" | "ANALYZING" | "ASSEMBLING" | "COMPLETED" | "FAILED" | "CANCELLED";
        SavedDomain: {
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            lastReportId?: string | null;
            normalizedQuery?: string;
            parameters?: components["schemas"]["AnalysisParameters"];
            query: string;
        };
        SaveDomainRequest: {
            parameters?: components["schemas"]["AnalysisParameters"];
            query: string;
        };
        SharedTopic: {
            appearances: components["schemas"]["TopicAppearance"][];
            /** @description Заголовок из того направления, где тема стоит выше всего. */
            title: string;
            /** @description Идентичность темы по методологии — тот же ключ, что у обратной связи, дельты и трассировки. Сопоставление идёт по нему, а не по заголовку. */
            trendKey: string;
        };
        /** @enum {string} */
        SourceClass: "PREPRINT" | "JOURNAL_ARTICLE" | "PATENT" | "CODE_REPOSITORY" | "NEWS" | "ANALYST_REPORT" | "STANDARD";
        SourceView: {
            apiKeyConfigured?: boolean;
            displayName: string;
            /** Format: int64 */
            documentCount?: number;
            enabled: boolean;
            id: string;
            lastRun?: components["schemas"]["IngestionRunView"];
            rateLimitPerMinute?: number;
            requiresApiKey?: boolean;
            sourceClass: components["schemas"]["SourceClass"];
        };
        SubmitResearchRequest: {
            parameters?: components["schemas"]["AnalysisParameters"];
            /** @example технологии в искусственном интеллекте */
            query: string;
            /**
             * @description Считать заново, не переиспользуя готовый отчёт. Пропускается **только** проверка свежести: `Idempotency-Key` по-прежнему схлопывает двойной клик, идущий анализ по-прежнему возвращается вместо второго запуска, квота по-прежнему списывается — пересчёт это заказ настоящей работы, а не освобождение от платы за неё.
             *
             *     По умолчанию выключено: значение по умолчанию, которое считает заново, превратило бы каждый обычный вопрос в полный анализ.
             * @default false
             */
            refresh?: boolean;
        };
        TermExplanation: {
            /** @description Все стадии конвейера по порядку, как их называет движок. Клиент рисует путь термина по этому списку, а не по своей копии: копия молча отстала бы в тот день, когда в конвейере появится новая стадия, и продолжила бы выглядеть правильной. */
            stages: string[];
            traces: {
                /** @description Термин, в который этот был слит при объединении синонимов. */
                canonicalTerm?: string | null;
                /** @description Числа, решившие исход — пороги и измеренные значения. */
                detail?: {
                    [key: string]: unknown;
                };
                /** @description Дошёл ли термин до отчёта. */
                inReport: boolean;
                outcome: string;
                /** @description Причина отказа словами, с которыми аналитик может что-то сделать. */
                reason?: string | null;
                /** @description Последняя достигнутая стадия. */
                stage: string;
                /** @description Термин в том виде, в каком его ключевал движок. */
                term: string;
            }[];
        };
        /** @description Трассировка ещё считается; ответ будет по тому же адресу. */
        TermExplanationPending: {
            /** @description Через сколько секунд спросить снова; то же, что в заголовке `Retry-After`. */
            retryAfterSeconds: number;
            /** @enum {string} */
            state: "RUNNING";
        };
        TimelinePoint: {
            documentCount: number;
            /** @description Degree of Diffusion (Yoon 2012) */
            dod?: number;
            /** @description Degree of Visibility (Yoon 2012) */
            dov?: number;
            /**
             * @example 2024
             * @example 2024-Q3
             */
            period: string;
        };
        TopicAppearance: {
            query: string;
            /** @description Место темы в этом направлении. Вторая позиция в одном и пятнадцатая в другом — другое утверждение, чем «есть в обоих». */
            rank: number;
            /** Format: uuid */
            reportId: string;
            /** Format: uuid */
            savedDomainId: string;
        };
        TopicOccurrence: {
            /** Format: date-time */
            generatedAt: string;
            /** @description Формулировка направления, как её написал человек */
            query: string;
            rank: number;
            /** Format: uuid */
            reportId: string;
            version: number;
        };
        TopicSearchResult: {
            topics: components["schemas"]["FoundTopic"][];
            /** @description Сколько вхождений просмотрено. Не размер корпуса: само это число упирается в предел выборки, поэтому отвечает на вопрос «сколько мы посмотрели», а не «сколько их есть». */
            totalOccurrences: number;
            /** @description Сколько тем нашлось всего. Знаменатель для показанных: без него «найдено 25» выдавало бы показанное за найденное, и сорок первая тема исчезала бы бесследно. */
            totalTopics: number;
            /** @description Упёрлись ли в предел выборки строк */
            truncated: boolean;
        };
        TrendFeedbackRequest: {
            comment?: string;
            /** @enum {string} */
            verdict: "RELEVANT" | "NOISE" | "ALREADY_KNOWN";
        };
        TrendFeedbackView: {
            /**
             * @description Оценка дана не в этом отчёте, а в другом по тому же направлению — как правило, в более ранней версии, ради которой перенос и сделан: отчёты неизменяемы, пересчёт создаёт новый, и без переноса разметка аналитика пропадала бы каждый квартал. Ограничения «строго раньше» намеренно нет: сказано ровно то, что проверено, — это другой отчёт того же направления.
             *
             *     Помечена как перенесённая, а не выдана за здешнюю: поставленная продуктом от имени аналитика пометка неотличима от его собственной, и он нашёл бы своё имя под суждением, которого не высказывал. Подтверждается обычным `PUT`.
             * @default false
             */
            carried?: boolean;
            comment?: string;
            /** Format: date-time */
            createdAt: string;
            /** @enum {string} */
            verdict: "RELEVANT" | "NOISE" | "ALREADY_KNOWN";
        };
        TrendReport: {
            /** Format: uuid */
            corpusSnapshotId: string;
            coverage: components["schemas"]["Coverage"];
            /**
             * @default methodology
             * @enum {string}
             */
            engine?: "methodology" | "signals";
            /** Format: date-time */
            generatedAt: string;
            hiddenTopics?: {
                title: string;
                trendKey: string;
            }[];
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            methodologyProfileId?: string;
            /** @example em-1.0.0 */
            methodologyVersion: string;
            /**
             * @default fast
             * @enum {string}
             */
            mode?: "fast" | "quality";
            normalizedQuery?: string;
            portrait?: components["schemas"]["DirectionPortrait"];
            /** Format: uuid */
            previousVersionId?: string | null;
            query: string;
            /** Format: uuid */
            researchRequestId: string;
            /** @example WEIGHTED_GEOMETRIC */
            scoreAggregator?: string;
            trends: components["schemas"]["RankedTrend"][];
            /** @default false */
            truncated?: boolean;
            version: number;
        };
        TriggerIngestionRequest: {
            /**
             * @default INCREMENTAL
             * @enum {string}
             */
            mode?: "INCREMENTAL" | "BACKFILL";
            query?: string;
            /** Format: date */
            windowFrom?: string;
            /** Format: date */
            windowTo?: string;
        };
        UnrecognizedDirection: {
            /** Format: date-time */
            firstSeen: string;
            /**
             * @description Показала ли система выход. Формулировка, от которой до известной статьи один щелчок,
             *     стоит куратору минуты; формулировка, на которую не предложено ничего, — это направление,
             *     о котором продукт не знает вовсе, и разбирать её надо первой.
             */
            hadAWayOut: boolean;
            /** Format: date-time */
            lastSeen: string;
            /** @description Ключ слияния — «ИИ» и «ии» одна задача, а не две */
            normalizedQuery: string;
            occurrences: number;
            /** @description Формулировка так, как её набрал аналитик */
            query: string;
            /** @description Что предлагалось в последний раз */
            suggestions?: string[];
        };
        UpdateSourceRequest: {
            enabled?: boolean;
            rateLimitPerMinute?: number;
        };
    };
    responses: {
        /** @description Конфликт состояния */
        ConflictProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Не найдено */
        NotFoundProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Превышен лимит запросов */
        RateLimitProblem: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Ошибка валидации */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ReportId: string;
        RequestId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listUnrecognizedDirections: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Очередь пополнения */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnrecognizedDirection"][];
                };
            };
        };
    };
    listKnownDirections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Известные формулировки в устойчивом порядке */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    resolveDirection: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Вердикт и ближайшие известные формулировки */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectionResolution"];
                };
            };
        };
    };
    listFeatures: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Состояние реестра */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeatureFlag"][];
                };
            };
        };
    };
    listIngestionRuns: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
                sourceId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница прогонов */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunPage"];
                };
            };
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отчёт */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendReport"];
                };
            };
            404: components["responses"]["NotFoundProblem"];
        };
    };
    getReportDelta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Дельта либо причина, по которой её нет */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDelta"];
                };
            };
            404: components["responses"]["NotFoundProblem"];
        };
    };
    explainReportTerms: {
        parameters: {
            query: {
                /** @description Термин; параметр можно повторить, но не более пяти раз. */
                term: string[];
            };
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Что произошло с каждым термином */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermExplanation"];
                };
            };
            /** @description Прогон запущен или ещё идёт; повторите тот же запрос через `Retry-After` секунд */
            202: {
                headers: {
                    /** @description Через сколько секунд спросить снова */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermExplanationPending"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            404: components["responses"]["NotFoundProblem"];
            /** @description Движок анализа не ответил на запрос трассировки */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    exportReport: {
        parameters: {
            query: {
                format: "json" | "csv" | "markdown";
            };
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Файл экспорта */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendReport"];
                    "text/csv": string;
                    "text/markdown": string;
                };
            };
            404: components["responses"]["NotFoundProblem"];
        };
    };
    getReportTrend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
                trendKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Тренд */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankedTrend"];
                };
            };
            404: components["responses"]["NotFoundProblem"];
        };
    };
    submitTrendFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
                trendKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrendFeedbackRequest"];
            };
        };
        responses: {
            /** @description Оценка сохранена */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendFeedbackView"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
    withdrawTrendFeedback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
                trendKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пометка снята */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFoundProblem"];
        };
    };
    listResearchRequests: {
        parameters: {
            query?: {
                /** @description Сузить до собственных запросов. Явное сужение, а не режим по умолчанию: тот, кому нужен свой список, об этом знает, а тот, кому нужен командный, о нём не догадывается. */
                onlyMine?: boolean;
                page?: number;
                size?: number;
                status?: components["schemas"]["ResearchStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Страница истории */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRequestPage"];
                };
            };
        };
    };
    submitResearchRequest: {
        parameters: {
            query?: never;
            header?: {
                /** @description Повтор с тем же ключом в течение 24 ч вернёт исходный запрос */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitResearchRequest"];
            };
        };
        responses: {
            /** @description Новой работы не начато: найден актуальный отчёт, анализ уже идёт либо это повтор по Idempotency-Key. Что именно — в поле `outcome`; готовый `reportId` есть только у `reused`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRequestView"];
                };
            };
            /** @description Запрос принят, выполняется асинхронно */
            202: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRequestView"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            429: components["responses"]["RateLimitProblem"];
        };
    };
    getResearchRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Текущее состояние */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRequestView"];
                };
            };
            404: components["responses"]["NotFoundProblem"];
        };
    };
    cancelResearchRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отменён */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResearchRequestView"];
                };
            };
            404: components["responses"]["NotFoundProblem"];
            /** @description Запрос уже в терминальном состоянии */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    streamResearchRequestEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                requestId: components["parameters"]["RequestId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Поток событий */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            404: components["responses"]["NotFoundProblem"];
        };
    };
    getQuota: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Остаток бюджета */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quota"];
                };
            };
        };
    };
    listSavedDomains: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedDomain"][];
                };
            };
        };
    };
    saveDomain: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveDomainRequest"];
            };
        };
        responses: {
            /** @description Сохранено */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedDomain"];
                };
            };
            409: components["responses"]["ConflictProblem"];
        };
    };
    deleteSavedDomain: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Удалено */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFoundProblem"];
        };
    };
    markDirectionSeen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Отмечено */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFoundProblem"];
        };
    };
    getRadarDigest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Состояние портфеля направлений */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RadarDigest"][];
                };
            };
        };
    };
    getDirectionOverlap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пересечение направлений портфеля */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectionOverlap"];
                };
            };
            404: components["responses"]["NotFoundProblem"];
        };
    };
    refreshRadar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Исход по каждому направлению */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RadarRefresh"][];
                };
            };
            404: components["responses"]["NotFoundProblem"];
        };
    };
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Список источников */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceView"][];
                };
            };
        };
    };
    updateSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSourceRequest"];
            };
        };
        responses: {
            /** @description Обновлено */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceView"];
                };
            };
            404: components["responses"]["NotFoundProblem"];
        };
    };
    triggerIngestionRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sourceId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TriggerIngestionRequest"];
            };
        };
        responses: {
            /** @description Прогон запущен */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRunView"];
                };
            };
            /** @description Прогон по этому источнику уже выполняется */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getOpenAlexQuota: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сумма по ключам, которые ответили на проверку; сами ключи не возвращаются */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenAlexQuota"];
                };
            };
        };
    };
    searchTopics: {
        parameters: {
            query: {
                /** @description Фрагмент названия темы, не короче двух символов */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Найденные темы и их вхождения */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicSearchResult"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            404: components["responses"]["NotFoundProblem"];
        };
    };
}
