/**
 * Generates `src/api/generated.ts` from the OpenAPI contract.
 *
 * The contract at `contracts/openapi/horizon-api.yaml` is the single source of truth
 * (see its `info.description`). The generated file is COMMITTED so that CI, review and
 * `npm ci` installs never drift from the checked-in types; re-run `npm run gen:api`
 * whenever the contract changes and commit the diff.
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const here = dirname(fileURLToPath(import.meta.url));
const contractPath = resolve(here, '../../contracts/openapi/horizon-api.yaml');
// Путь вывода можно перенаправить: так проверка синхронности генерирует во временный файл и
// сравнивает, не трогая рабочее дерево. Проверка, которая перезаписывает то, что проверяет,
// оставляет после неудачи изменённый репозиторий — и её начинают запускать реже.
const outputPath = process.env.HORIZON_GEN_OUT
  ? resolve(process.env.HORIZON_GEN_OUT)
  : resolve(here, '../src/api/generated.ts');

const banner = `/* eslint-disable */
/**
 * DO NOT EDIT — generated by \`npm run gen:api\` from
 * contracts/openapi/horizon-api.yaml (Horizon Public API v1.0.0).
 *
 * Regenerate after every contract change and commit the result.
 */

`;

async function main() {
  await readFile(contractPath, 'utf8'); // fail fast with a clear ENOENT if the contract moved
  const ast = await openapiTS(pathToFileURL(contractPath), {
    alphabetize: true,
    emptyObjectsUnknown: true,
    defaultNonNullable: false,
  });
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, banner + astToString(ast), 'utf8');
  console.log(`generated ${outputPath}`);
}

main().catch((error) => {
  console.error('[gen:api] failed:', error);
  process.exitCode = 1;
});
