/**
 * English locale.
 *
 * Typed as a deep-partial of the Russian reference dictionary: the app is
 * shipped Russian-first (BR scope: RU/EN only, RU default), and this file exists
 * so that switching `?lang=en` produces English wherever a string has been
 * translated and Russian everywhere else — never a blank or a missing-key token.
 *
 * Translation status: domain vocabulary and the error catalogue are complete;
 * page-level prose is not yet extracted.
 */
import type { Dictionary } from './ru';

/**
 * The reference dictionary is `as const`, so its leaves are literal types. A
 * translation must be *any* string, not that exact Russian literal — hence the
 * widening of string leaves here.
 */
type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends string ? string : DeepPartial<T[K]>;
};

export const en: DeepPartial<Dictionary> = {
  common: {
    appName: 'Hiddenjem',
    tagline: 'Emerging technology trends',
    loading: 'Loading…',
    retry: 'Retry',
    cancel: 'Cancel',
    close: 'Close',
    save: 'Save',
    delete: 'Delete',
    search: 'Search',
    back: 'Back',
    more: 'Details',
    of: 'of',
    yes: 'Yes',
    no: 'No',
    never: 'never',
    copy: 'Copy',
    copied: 'Copied',
    apply: 'Apply',
    reset: 'Reset',
    page: 'Page',
    nothingFound: 'Nothing found',
    optional: 'optional',
  },

  history: {
    scopeMine: 'My requests',
    scopeOrganization: 'Whole organization',
    scopeLabel: 'Whose requests to show',
  },

  nav: {
    research: 'Search',
    history: 'History',
    radar: 'Radar',
    topics: 'Topics',
    saved: 'Saved',
    sources: 'Sources',
    admin: 'Administration',
    lexicon: 'Direction lexicon',
    theme: 'Theme',
    themeLight: 'Light',
    themeDark: 'Dark',
    themeSystem: 'System',
    skipToContent: 'Skip to content',
  },

  sourceClass: {
    PREPRINT: 'Preprint',
    JOURNAL_ARTICLE: 'Journal article',
    PATENT: 'Patent',
    CODE_REPOSITORY: 'Code repository',
    NEWS: 'News',
    ANALYST_REPORT: 'Analyst report',
    STANDARD: 'Standard',
  },

  credibility: {
    HIGH: 'high',
    MEDIUM: 'medium',
    LOW: 'reduced',
  },

  credibilityHint: {
    HIGH: 'Peer-reviewed publication, patent record, standard, or an official government/academic domain',
    MEDIUM:
      'Preprint, analyst report, or an organisation-owned repository: a primary source without review',
    LOW: 'Trade media, press release, social network, or a personal platform: an early indicator that needs confirmation',
  },

  keyPredictors: {
    label: 'Key predictors: ',
    firstYear: 'first seen {year}',
    growthAbsolute: '×{factor} publications per year',
    growthRelative: '×{factor} share of the direction per year',
    burst: '{base}, burst since {period}',
    sourceTypes: '{organizations}, {count}\u00A0{types} of sources',
    weakness: '{documents}{span} against {leader} for the most frequent topic of the direction',
    span: ' in {years}\u00A0yr',
    industry: '{percent}% of works with a corporate affiliation',
    organization: { one: 'organisation', few: 'organisations', many: 'organisations' },
    type: { one: 'type', few: 'types', many: 'types' },
    work: { one: 'work', few: 'works', many: 'works' },
    patent: { one: 'patent', few: 'patents', many: 'patents' },
  },

  evidence: {
    language: 'Original language',
    languageUnknown: 'language not stated by the source',
    credibility: 'Credibility',
    notIndependent: 'not an independent account',
    translated: 'machine translation',
    generated: 'summary generated by a model',
    originalTitle: 'original title',
  },

  exclusions: {
    title: 'What did not make the report, and why',
    description:
      'The exclusion logic for mature trends, mass-adopted technologies, marketing hype, and noise. A count without names cannot be checked, so every reason carries examples of the phrases it removed.',
    columnReason: 'Reason',
    columnCount: 'Candidates',
    columnExamples: 'Examples',
    empty: 'The engine sent no exclusion reasons — this report predates the block.',
  },

  researchStatus: {
    PENDING: 'Queued',
    COLLECTING: 'Collecting',
    ANALYZING: 'Analyzing',
    ASSEMBLING: 'Assembling',
    COMPLETED: 'Completed',
    FAILED: 'Failed',
    CANCELLED: 'Cancelled',
  },

  stage: {
    QUEUED: 'Queued',
    COLLECTING: 'Collecting',
    ANALYZING: 'Analyzing',
    ASSEMBLING: 'Assembling',
    DONE: 'Done',
  },

  stageHint: {
    QUEUED: 'The request has been accepted and is waiting for a free worker',
    COLLECTING:
      'Publications, patents and repositories are being collected from the connected sources',
    ANALYZING: 'Terms are extracted and clustered, emergence indicators are computed',
    ASSEMBLING: 'Trends are ranked, evidence and case examples are selected',
    DONE: 'The report is ready',
  },

  mode: {
    label: 'Analysis mode',
    fast: 'Fast',
    quality: 'Thorough',
  },

  modeDuration: {
    fast: 'up to 20 minutes',
    quality: '30–40 minutes',
  },

  modeHint: {
    fast: 'An answer within the 20-minute SLA: deep research gets 5.5 minutes.',
    quality:
      'Deep research for up to 20 minutes reading three times as many pages; the whole analysis takes 30–40 minutes.',
  },

  lifecycle: {
    EMBRYONIC: 'Embryonic',
    EMERGING: 'Emerging',
    ACCELERATING: 'Accelerating',
    MATURING: 'Maturing',
  },

  lifecycleHint: {
    EMBRYONIC: 'Publication volume below the direction’s lower quartile, with a positive trend',
    EMERGING: 'Volume between q25 and q60, steady growth (β > 0.20)',
    ACCELERATING: 'Fast growth (β > 0.50) with a burst or a substantial volume',
    MATURING: 'Growth has slowed (β ≤ 0.20), or the patent share is high at a large volume',
  },

  indicator: {
    novelty: 'Novelty',
    growth: 'Growth',
    diffusion: 'Diffusion',
    weakness: 'Signal weakness',
    coherence: 'Coherence',
    impact: 'Impact potential',
  },

  indicatorHint: {
    novelty:
      'How recently the topic appeared. Exponential decay from the first credible year (τ = 3 years).',
    growth:
      'How fast and how steadily the publication count grows: the slope of a log-linear regression over the window’s periods.',
    diffusion:
      'How far the topic has spread beyond a single group: entropy across source classes, breadth of organisations and venues.',
    weakness:
      'How quiet the topic still is. A topic that is already loud is not a weak signal and scores low.',
    coherence:
      'Tells a technological concept from an accidental n-gram: embedding proximity and NPMI of the terms.',
    impact:
      'Signs of the move from research to application: citations, patent share, industry participation.',
  },

  verdict: {
    RELEVANT: 'Relevant',
    NOISE: 'Noise',
    ALREADY_KNOWN: 'Already known',
    carried: 'from another report',
    carriedHint:
      'Your verdict for this direction, given in another report. It has not been confirmed here yet.',
  },

  stability: {
    // Подписи короткие по той же причине, что и в русском словаре: они стоят в ряду фактов
    // карточки, рядом с числом документов, и длинное объяснение читалось бы как сообщение о
    // неисправности.
    immovable: 'Rank does not depend on the weights',
    holds: 'Stays in the report under every weighting: rank {best}–{worst}',
    slips: 'Drops out of the report under other weightings: rank {best}–{worst}',
    scenarios: 'Weightings checked: {count}',
    // Не оценочно и здесь: продукт сообщает факт об источниках, вывод остаётся за аналитиком.
    stageFromOnePoint: 'Stage computed from a single point of the series — there is no trend in it',
    stageFromTwoPoints:
      'Stage computed from two points of the series — the data cannot contradict such a trend',
    earlierMentions:
      'Individual documents since {since} — until {credible} the topic rested on a single source',
    weakDirection: '{inside} of the topic’s {total} documents belong to your direction',
  },

  lexicon: {
    title: 'Queue for extending the direction lexicon',
    description:
      'Wordings the crosswalk does not know. At the top are those the product could suggest nothing for: the analyst got a red banner and left with nothing.',
    columnQuery: 'As the analyst typed it',
    columnOccurrences: 'Times asked',
    columnWayOut: 'Was there a way out',
    columnSuggestions: 'What was suggested',
    columnLastSeen: 'Last seen',
    wayOutYes: 'a suggestion was offered',
    wayOutNo: 'nothing was offered',
    noSuggestions: '—',
    emptyTitle: 'The lexicon covers everything that was asked',
    emptyBody:
      'No direction wording was left unrecognised. This is a statement about the lexicon, not an absence of data.',
  },

  warning: {
    lowEvidenceTitle: 'Thin evidence base',
    lowEvidenceBody:
      'Confidence below 0.40: there are few documents, or they are uniform. The trend is shown but needs manual checking before it informs a decision.',
    suppressedRestore: 'Restore',
    suppressedTitle: 'Some topics are hidden by your mark',
    suppressedBody:
      'Topics hidden: {count}. You marked them as “not a technology”, and the engine removed them before the top-N selection — the freed places went to the next candidates. The list is complete, but its composition depends on your marks and not on the data alone.',
    suppressedByRequesterBody:
      'Topics hidden: {count}. They were marked “not a technology” by the person who requested the report, and the engine removed them before the top-N selection — the freed places went to the next candidates. Reports are visible to the whole organisation, but marks apply only to their author’s requests: yours were not applied here. Run the analysis again to get a composition based on your own marks.',
    suppressedMixedBody:
      'Topics hidden: {count}, of them yours: {named}. The rest were marked by the person who requested the report: reports are visible to the whole organisation, while marks apply to their author’s requests. Run the analysis again to get a composition based on your marks alone.',
    deltaNoPreviousVersion:
      'This is the first version of the report for this direction — there is nothing to compare with yet.',
    deltaMethodologyChanged:
      'The way scores are computed changed between the runs: the engine, its version or the score aggregator. A difference of scores measured with different rulers would be a change of scale rather than a change in the field, so no comparison was made. The computation version is listed in the “Analysis coverage” block.',
    corpusTruncatedTitle: 'The corpus was not covered in full',
    corpusTruncatedBody:
      'The direction has more documents than the engine takes into a single analysis, so part of the literature was not examined. The topics below are computed correctly, but completeness of the review is not guaranteed: narrow the direction or the window to cover it entirely.',
    partialTitle: 'Incomplete source coverage',
    partialBody: 'Some sources were unavailable during the run; the output may be incomplete.',
    directionUnrecognizedTitle: 'Direction not recognised',
    directionUnrecognizedBody:
      'The engine could not map the requested direction onto the subject-code lexicon the corpus is labelled with. The list of topics below does not depend on the question asked and cannot serve as grounds for a decision.',
    directionUnrecognizedHint:
      'Try rewording the direction — for example, “quantum computing” instead of “quantum computation”. If the wording is right, the direction has to be added to the crosswalk.',
    directionSuggestionsLead: 'You may have meant:',
    truncatedTitle: 'Report truncated',
    truncatedBody: 'Fewer trends passed the credibility rules than the number requested.',
    cachedTitle: 'Result from cache',
    cachedBody:
      'A previously computed report for this direction is shown. A colleague may have ordered it: results are visible to the whole organisation, so the same corpus is not paid for twice.',
    replayBody:
      'This request has already been submitted: its result is shown, and no second analysis was started.',
    runningTitle: 'Analysis already running',
    runningBody:
      'A run for this direction was started earlier — it has been opened, no second one was launched, and no quota was spent.',
  },

  organizationType: {
    COMPANY: 'Company',
    UNIVERSITY: 'University',
    RESEARCH_INSTITUTE: 'Research institute',
    GOVERNMENT: 'Government',
    NONPROFIT: 'Non-profit',
  },

  runStatus: {
    RUNNING: 'Running',
    COMPLETED: 'Completed',
    PARTIAL: 'Partial',
    FAILED: 'Failed',
  },

  runMode: {
    INCREMENTAL: 'Incremental',
    BACKFILL: 'Backfill',
    ON_DEMAND: 'On demand',
  },

  error: {
    title: 'The operation could not be completed',
    unknown: 'An unexpected error occurred.',
    unknownAction: 'Try again. If the error persists, contact your administrator.',
    network: 'No connection to the server.',
    networkAction: 'Check your network connection and try again.',
    contract: 'The server returned data in an unexpected format.',
    contractAction:
      'The UI and API versions have likely diverged. Reload the page; if that does not help, contact your administrator.',
    details: 'Technical details',
    traceId: 'Trace ID',
    fieldErrors: 'Field errors',

    'validation-error': 'The request failed validation.',
    'validation-errorTitle': 'Request validation failed',
    'validation-errorAction': 'Correct the highlighted fields and submit again.',
    'malformed-request': 'Malformed request.',
    'malformed-requestTitle': 'Malformed request',
    'malformed-requestAction': 'Reload the page and repeat the action.',
    'not-found': 'The requested object was not found.',
    'not-foundTitle': 'Resource not found',
    'not-foundAction': 'It may have been deleted. Return to the list.',
    conflict: 'The action conflicts with the current state of the object.',
    conflictTitle: 'State conflict',
    conflictAction: 'Reload the page to see the current state.',
    'illegal-state-transition': 'Illegal state transition.',
    'illegal-state-transitionTitle': 'Illegal state transition',
    'illegal-state-transitionAction': 'Reload the page: the state has already changed.',
    'quota-exceeded': 'Request quota exceeded.',
    'quota-exceededTitle': 'Request quota exceeded',
    'quota-exceededAction': 'Wait for the quota to reset or contact an administrator.',
    'rate-limited': 'Too many requests in a row.',
    'rate-limitedTitle': 'Too many requests',
    'rate-limitedAction': 'Wait a moment and retry.',
    'upstream-unavailable': 'An upstream data source is unavailable.',
    'upstream-unavailableTitle': 'External source unavailable',
    'upstream-unavailableAction': 'Retry later — the result may be incomplete.',
    'analysis-failed': 'The analysis did not complete.',
    'analysis-failedTitle': 'Analysis did not finish',
    'analysis-failedAction': 'Run the analysis again.',
    'internal-error': 'Internal service error.',
    'internal-errorTitle': 'Internal service error',
    'internal-errorAction': 'Retry later. The trace ID will help support.',
  },

  state: {
    emptyTitle: 'Nothing here yet',
    errorTitle: 'Could not load data',
    loadingLabel: 'Loading',
  },
};
